// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/jflex/GoLiteLexer.jflex

package com.golite.lexer;

import com.golite.reports.ErrorType;
import com.golite.reports.ReportCollector;

import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.List;


@SuppressWarnings("fallthrough")
public class GoLiteLexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int RUNE = 4;
  public static final int BLOCK_COMMENT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\36\u0100\1\u0400\u1001\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\1"+
    "\1\5\1\6\2\0\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\4\22\1\23"+
    "\1\22\1\24\3\22\1\25\1\26\1\27\1\30\1\31"+
    "\2\0\32\32\1\0\1\33\2\0\1\32\1\0\1\34"+
    "\1\35\1\36\1\32\1\37\1\40\1\41\1\32\1\42"+
    "\1\32\1\43\1\44\1\32\1\45\1\46\2\32\1\47"+
    "\1\50\1\51\1\52\1\53\4\32\1\54\1\55\1\56"+
    "\7\0\1\3\u01a2\0\2\3\326\0\u0100\3\377\0\1\57";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\1\1\21\1\22\1\23\1\24\13\25"+
    "\1\26\1\1\1\27\1\2\1\30\1\31\1\32\1\0"+
    "\1\30\1\33\1\34\1\2\1\35\1\36\1\37\1\2"+
    "\1\0\1\40\1\41\1\42\1\43\7\25\1\44\6\25"+
    "\1\45\1\46\1\47\1\50\6\25\1\51\1\52\1\53"+
    "\3\25\1\54\1\55\2\25\1\56\2\25\1\57\1\25"+
    "\1\60\1\61\1\25\1\62\4\25\1\63\1\25\1\64"+
    "\1\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\360\0\300\0\u0120"+
    "\0\300\0\300\0\u0150\0\300\0\300\0\300\0\300\0\300"+
    "\0\300\0\300\0\300\0\u0180\0\u01b0\0\u01e0\0\300\0\u0210"+
    "\0\u0240\0\u0270\0\u02a0\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390"+
    "\0\u03c0\0\u03f0\0\u0420\0\u0450\0\u0480\0\300\0\u04b0\0\300"+
    "\0\300\0\u04e0\0\300\0\300\0\u0510\0\u0540\0\300\0\300"+
    "\0\u0570\0\300\0\300\0\300\0\u05a0\0\u05d0\0\300\0\300"+
    "\0\300\0\300\0\u0600\0\u0630\0\u0660\0\u0690\0\u06c0\0\u06f0"+
    "\0\u0720\0\u02a0\0\u0750\0\u0780\0\u07b0\0\u07e0\0\u0810\0\u0840"+
    "\0\300\0\300\0\300\0\u05d0\0\u0870\0\u08a0\0\u08d0\0\u0900"+
    "\0\u0930\0\u0960\0\u02a0\0\u02a0\0\u02a0\0\u0990\0\u09c0\0\u09f0"+
    "\0\u02a0\0\u02a0\0\u0a20\0\u0a50\0\u02a0\0\u0a80\0\u0ab0\0\u02a0"+
    "\0\u0ae0\0\u02a0\0\u02a0\0\u0b10\0\u02a0\0\u0b40\0\u0b70\0\u0ba0"+
    "\0\u0bd0\0\u02a0\0\u0c00\0\u02a0\0\u02a0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\0\1\6\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\3\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\5\1\33\1\34\1\35\1\36\1\37\1\33"+
    "\1\40\2\33\1\41\1\33\1\42\1\43\1\44\1\33"+
    "\1\45\1\46\1\47\1\50\1\51\2\52\1\53\3\52"+
    "\1\54\24\52\1\55\24\52\2\56\1\57\6\56\1\60"+
    "\21\56\1\55\24\56\14\51\1\61\43\51\61\0\1\6"+
    "\2\0\1\6\103\0\1\62\37\0\1\63\63\0\1\64"+
    "\4\0\1\65\56\0\1\66\1\0\3\25\63\0\1\67"+
    "\57\0\1\70\57\0\1\71\57\0\1\72\51\0\3\33"+
    "\5\0\1\33\1\0\20\33\26\0\3\33\5\0\1\33"+
    "\1\0\12\33\1\73\1\74\4\33\26\0\3\33\5\0"+
    "\1\33\1\0\12\33\1\75\5\33\26\0\3\33\5\0"+
    "\1\33\1\0\10\33\1\76\7\33\26\0\3\33\5\0"+
    "\1\33\1\0\1\77\7\33\1\100\1\33\1\101\5\33"+
    "\26\0\3\33\5\0\1\33\1\0\4\33\1\102\4\33"+
    "\1\103\6\33\26\0\3\33\5\0\1\33\1\0\6\33"+
    "\1\104\11\33\26\0\3\33\5\0\1\33\1\0\16\33"+
    "\1\105\1\33\26\0\3\33\5\0\1\33\1\0\15\33"+
    "\1\106\2\33\26\0\3\33\5\0\1\33\1\0\13\33"+
    "\1\107\4\33\26\0\3\33\5\0\1\33\1\0\1\110"+
    "\17\33\61\0\1\111\2\0\2\52\1\0\3\52\1\0"+
    "\24\52\1\0\24\52\6\0\1\112\2\0\1\112\21\0"+
    "\1\112\11\0\1\112\1\0\1\112\1\0\1\112\6\0"+
    "\2\56\1\0\6\56\1\0\21\56\1\0\24\56\21\0"+
    "\1\113\36\0\2\65\1\0\1\65\1\0\53\65\22\0"+
    "\3\114\55\0\3\33\5\0\1\33\1\0\12\33\1\115"+
    "\5\33\26\0\3\33\5\0\1\33\1\0\3\33\1\116"+
    "\14\33\26\0\3\33\5\0\1\33\1\0\11\33\1\117"+
    "\6\33\26\0\3\33\5\0\1\33\1\0\14\33\1\120"+
    "\3\33\26\0\3\33\5\0\1\33\1\0\10\33\1\121"+
    "\7\33\26\0\3\33\5\0\1\33\1\0\12\33\1\122"+
    "\5\33\26\0\3\33\5\0\1\33\1\0\13\33\1\123"+
    "\4\33\26\0\3\33\5\0\1\33\1\0\15\33\1\124"+
    "\2\33\26\0\3\33\5\0\1\33\1\0\10\33\1\125"+
    "\7\33\26\0\3\33\5\0\1\33\1\0\11\33\1\126"+
    "\6\33\26\0\3\33\5\0\1\33\1\0\13\33\1\127"+
    "\4\33\26\0\3\33\5\0\1\33\1\0\16\33\1\130"+
    "\1\33\26\0\3\33\5\0\1\33\1\0\13\33\1\131"+
    "\4\33\26\0\3\33\5\0\1\33\1\0\10\33\1\132"+
    "\7\33\26\0\3\33\5\0\1\33\1\0\1\133\17\33"+
    "\26\0\3\33\5\0\1\33\1\0\15\33\1\134\2\33"+
    "\26\0\3\33\5\0\1\33\1\0\3\33\1\135\14\33"+
    "\26\0\3\33\5\0\1\33\1\0\14\33\1\136\3\33"+
    "\26\0\3\33\5\0\1\33\1\0\1\137\17\33\26\0"+
    "\3\33\5\0\1\33\1\0\3\33\1\140\14\33\26\0"+
    "\3\33\5\0\1\33\1\0\6\33\1\141\11\33\26\0"+
    "\3\33\5\0\1\33\1\0\3\33\1\142\14\33\26\0"+
    "\3\33\5\0\1\33\1\0\7\33\1\143\10\33\26\0"+
    "\3\33\5\0\1\33\1\0\6\33\1\144\11\33\26\0"+
    "\3\33\5\0\1\33\1\0\3\33\1\145\14\33\26\0"+
    "\3\33\5\0\1\33\1\0\15\33\1\146\2\33\26\0"+
    "\3\33\5\0\1\33\1\0\11\33\1\147\6\33\26\0"+
    "\3\33\5\0\1\33\1\0\11\33\1\150\6\33\26\0"+
    "\2\33\1\151\5\0\1\33\1\0\20\33\26\0\3\33"+
    "\5\0\1\33\1\0\5\33\1\152\12\33\26\0\3\33"+
    "\5\0\1\33\1\0\16\33\1\153\1\33\26\0\1\33"+
    "\1\154\1\33\5\0\1\33\1\0\20\33\26\0\3\33"+
    "\5\0\1\33\1\0\3\33\1\155\14\33\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3120];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\1\1\1\11\1\1\2\11\1\1\10\11"+
    "\3\1\1\11\16\1\1\11\1\1\2\11\1\1\2\11"+
    "\1\0\1\1\2\11\1\1\3\11\1\1\1\0\4\11"+
    "\16\1\3\11\42\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    // este colector guarda los errores lexicos que aparecen durante el recorrido.
    private final ReportCollector reportCollector;

    // esta lista conserva todos los tokens reconocidos por el scanner.
    private final List<Token> tokens = new ArrayList<>();

    // este buffer arma cadenas y runas antes de convertirlas en token.
    private final StringBuilder buffer = new StringBuilder();

    // estas posiciones guardan el inicio real del token actual.
    private int tokenLine;
    private int tokenColumn;

    // este valor ayuda a decidir si un salto de linea debe generar punto y coma.
    private TokenType previousTokenType;

    /** crea un lexer nuevo desde texto en memoria. */
    public GoLiteLexer(String source, ReportCollector reportCollector) {
        this(new StringReader(source == null ? "" : source), reportCollector);
    }

    /** crea un lexer nuevo desde cualquier reader. */
    public GoLiteLexer(Reader reader, ReportCollector reportCollector) {
        this.zzReader = reader;
        this.reportCollector = reportCollector;
    }

    /** recorre todo el archivo y devuelve la lista completa de tokens. */
    public List<Token> scanTokens() throws IOException {
        Token token;
        while ((token = yylex()) != null) {
            tokens.add(token);
            previousTokenType = token.type();
            if (token.type() == TokenType.EOF) {
                break;
            }
        }
        return List.copyOf(tokens);
    }

    /** crea un token usando la posicion actual del scanner. */
    private Token buildToken(TokenType type, Object literal) {
        return new Token(type, yytext(), literal, tokenLine, tokenColumn);
    }

    /** crea un token usando una imagen textual ya armada a mano. */
    private Token buildToken(TokenType type, Object literal, String lexeme, int line, int column) {
        return new Token(type, lexeme, literal, line, column);
    }

    /** registra un error lexico sin detener el escaneo. */
    private void lexicalError(String message) {
        reportCollector.addError(ErrorType.LEXICAL, yyline + 1, yycolumn + 1, message);
    }

    /** prepara el scanner para leer una cadena. */
    private void startString() {
        buffer.setLength(0);
        tokenLine = yyline + 1;
        tokenColumn = yycolumn + 1;
        yybegin(STRING);
    }

    /** prepara el scanner para leer una runa. */
    private void startRune() {
        buffer.setLength(0);
        tokenLine = yyline + 1;
        tokenColumn = yycolumn + 1;
        yybegin(RUNE);
    }

    /** cierra una cadena y la convierte en token. */
    private Token finishString() {
        yybegin(YYINITIAL);
        return buildToken(TokenType.STRING_LITERAL, buffer.toString(), "\"" + buffer + "\"", tokenLine, tokenColumn);
    }

    /** cierra una runa y valida que tenga un solo caracter. */
    private Token finishRune() {
        yybegin(YYINITIAL);
        if (buffer.codePointCount(0, buffer.length()) != 1) {
            lexicalError("runa invalida");
            return null;
        }
        int codePoint = buffer.codePointAt(0);
        return buildToken(TokenType.RUNE_LITERAL, codePoint, "'" + buffer + "'", tokenLine, tokenColumn);
    }

    /** decodifica escapes simples para cadenas y runas. */
    private char decodeEscape(char escaped) {
        return switch (escaped) {
            case 'n' -> '\n';
            case 't' -> '\t';
            case 'r' -> '\r';
            case '"' -> '"';
            case '\'' -> '\'';
            case '\\' -> '\\';
            default -> escaped;
        };
    }

    /** decide si un salto de linea puede convertirse en punto y coma. */
    private boolean canInsertSemicolon(TokenType type) {
        if (type == null) {
            return false;
        }
        return switch (type) {
            case IDENTIFIER, INT_LITERAL, FLOAT_LITERAL, STRING_LITERAL, RUNE_LITERAL,
                 BOOL_LITERAL, NIL_LITERAL, RPAREN, RBRACE, BREAK, CONTINUE -> true;
            default -> false;
        };
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public GoLiteLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              return buildToken(TokenType.EOF, null, "", yyline + 1, yycolumn + 1);
            }  // fall though
            case 110: break;
            case STRING: {
              lexicalError("cadena sin cerrar");
    return buildToken(TokenType.EOF, null, "", yyline + 1, yycolumn + 1);
            }  // fall though
            case 111: break;
            case RUNE: {
              lexicalError("runa sin cerrar");
    return buildToken(TokenType.EOF, null, "", yyline + 1, yycolumn + 1);
            }  // fall though
            case 112: break;
            case BLOCK_COMMENT: {
              lexicalError("comentario de bloque sin cerrar");
    return buildToken(TokenType.EOF, null, "", yyline + 1, yycolumn + 1);
            }  // fall though
            case 113: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { lexicalError("caracter no reconocido: '" + yytext() + "'");
            }
          // fall through
          case 54: break;
          case 2:
            { return null;
            }
          // fall through
          case 55: break;
          case 3:
            { if (canInsertSemicolon(previousTokenType)) {
        tokenLine = yyline + 1;
        tokenColumn = yycolumn + 1;
        return buildToken(TokenType.SEMICOLON, null, ";", tokenLine, tokenColumn);
    }
    return null;
            }
          // fall through
          case 56: break;
          case 4:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.BANG, null);
            }
          // fall through
          case 57: break;
          case 5:
            { startString();
            }
          // fall through
          case 58: break;
          case 6:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.PERCENT, null);
            }
          // fall through
          case 59: break;
          case 7:
            { startRune();
            }
          // fall through
          case 60: break;
          case 8:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.LPAREN, null);
            }
          // fall through
          case 61: break;
          case 9:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.RPAREN, null);
            }
          // fall through
          case 62: break;
          case 10:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.STAR, null);
            }
          // fall through
          case 63: break;
          case 11:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.PLUS, null);
            }
          // fall through
          case 64: break;
          case 12:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.COMMA, null);
            }
          // fall through
          case 65: break;
          case 13:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.MINUS, null);
            }
          // fall through
          case 66: break;
          case 14:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.DOT, null);
            }
          // fall through
          case 67: break;
          case 15:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.SLASH, null);
            }
          // fall through
          case 68: break;
          case 16:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.INT_LITERAL, Long.valueOf(yytext()));
            }
          // fall through
          case 69: break;
          case 17:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.SEMICOLON, null);
            }
          // fall through
          case 70: break;
          case 18:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.LESS, null);
            }
          // fall through
          case 71: break;
          case 19:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.ASSIGN, null);
            }
          // fall through
          case 72: break;
          case 20:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.GREATER, null);
            }
          // fall through
          case 73: break;
          case 21:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.IDENTIFIER, null);
            }
          // fall through
          case 74: break;
          case 22:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.LBRACE, null);
            }
          // fall through
          case 75: break;
          case 23:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.RBRACE, null);
            }
          // fall through
          case 76: break;
          case 24:
            { buffer.append(yytext());
            }
          // fall through
          case 77: break;
          case 25:
            { lexicalError("cadena sin cerrar");
    yybegin(YYINITIAL);
            }
          // fall through
          case 78: break;
          case 26:
            { return finishString();
            }
          // fall through
          case 79: break;
          case 27:
            { lexicalError("runa sin cerrar");
    yybegin(YYINITIAL);
            }
          // fall through
          case 80: break;
          case 28:
            { Token token = finishRune();
    if (token != null) {
        return token;
    }
            }
          // fall through
          case 81: break;
          case 29:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.BANG_EQUAL, null);
            }
          // fall through
          case 82: break;
          case 30:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.AND_AND, null);
            }
          // fall through
          case 83: break;
          case 31:
            { yybegin(BLOCK_COMMENT);
    return null;
            }
          // fall through
          case 84: break;
          case 32:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.COLON_EQUAL, null);
            }
          // fall through
          case 85: break;
          case 33:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.LESS_EQUAL, null);
            }
          // fall through
          case 86: break;
          case 34:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.EQUAL_EQUAL, null);
            }
          // fall through
          case 87: break;
          case 35:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.GREATER_EQUAL, null);
            }
          // fall through
          case 88: break;
          case 36:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.IF, null);
            }
          // fall through
          case 89: break;
          case 37:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.OR_OR, null);
            }
          // fall through
          case 90: break;
          case 38:
            { buffer.append(decodeEscape(yytext().charAt(1)));
            }
          // fall through
          case 91: break;
          case 39:
            { yybegin(YYINITIAL);
    return null;
            }
          // fall through
          case 92: break;
          case 40:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.FLOAT_LITERAL, Double.valueOf(yytext()));
            }
          // fall through
          case 93: break;
          case 41:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.FOR, null);
            }
          // fall through
          case 94: break;
          case 42:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.TYPE_INT, null);
            }
          // fall through
          case 95: break;
          case 43:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.NIL_LITERAL, null);
            }
          // fall through
          case 96: break;
          case 44:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.VAR, null);
            }
          // fall through
          case 97: break;
          case 45:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.TYPE_BOOL, null);
            }
          // fall through
          case 98: break;
          case 46:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.ELSE, null);
            }
          // fall through
          case 99: break;
          case 47:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.TYPE_RUNE, null);
            }
          // fall through
          case 100: break;
          case 48:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.BOOL_LITERAL, Boolean.TRUE);
            }
          // fall through
          case 101: break;
          case 49:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.BREAK, null);
            }
          // fall through
          case 102: break;
          case 50:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.BOOL_LITERAL, Boolean.FALSE);
            }
          // fall through
          case 103: break;
          case 51:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.TYPE_STRING, null);
            }
          // fall through
          case 104: break;
          case 52:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.TYPE_FLOAT64, null);
            }
          // fall through
          case 105: break;
          case 53:
            { tokenLine = yyline + 1;
    tokenColumn = yycolumn + 1;
    return buildToken(TokenType.CONTINUE, null);
            }
          // fall through
          case 106: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
