
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package com.golite.parser;

/** CUP generated class containing symbol constants. */
public class GoLiteSym {
  /* terminals */
  public static final int RUNE_LITERAL = 18;
  public static final int STRING_LITERAL = 17;
  public static final int AND_AND = 27;
  public static final int SLASH = 24;
  public static final int PLUS_ASSIGN = 36;
  public static final int TYPE_FLOAT64 = 10;
  public static final int MINUS_MINUS = 40;
  public static final int LPAREN = 44;
  public static final int GREATER = 33;
  public static final int CONTINUE = 8;
  public static final int TYPE_RUNE = 13;
  public static final int BANG_EQUAL = 30;
  public static final int LESS = 31;
  public static final int FOR = 6;
  public static final int MINUS = 22;
  public static final int STAR = 23;
  public static final int RPAREN = 45;
  public static final int SEMICOLON = 43;
  public static final int COMMA = 42;
  public static final int BANG = 26;
  public static final int OR_OR = 28;
  public static final int LESS_EQUAL = 32;
  public static final int TYPE_INT = 9;
  public static final int PLUS = 21;
  public static final int ASSIGN = 35;
  public static final int IF = 4;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int PLUS_PLUS = 39;
  public static final int GREATER_EQUAL = 34;
  public static final int error = 1;
  public static final int PERCENT = 25;
  public static final int BREAK = 7;
  public static final int LBRACE = 46;
  public static final int ELSE = 5;
  public static final int NIL_LITERAL = 20;
  public static final int TYPE_STRING = 12;
  public static final int RBRACE = 47;
  public static final int KW_FUNC = 2;
  public static final int SHORT_DECL = 38;
  public static final int FLOAT_LITERAL = 16;
  public static final int TYPE_BOOL = 11;
  public static final int MINUS_ASSIGN = 37;
  public static final int VAR = 3;
  public static final int EQUAL_EQUAL = 29;
  public static final int BOOL_LITERAL = 19;
  public static final int INT_LITERAL = 15;
  public static final int IDENTIFIER = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "KW_FUNC",
  "VAR",
  "IF",
  "ELSE",
  "FOR",
  "BREAK",
  "CONTINUE",
  "TYPE_INT",
  "TYPE_FLOAT64",
  "TYPE_BOOL",
  "TYPE_STRING",
  "TYPE_RUNE",
  "IDENTIFIER",
  "INT_LITERAL",
  "FLOAT_LITERAL",
  "STRING_LITERAL",
  "RUNE_LITERAL",
  "BOOL_LITERAL",
  "NIL_LITERAL",
  "PLUS",
  "MINUS",
  "STAR",
  "SLASH",
  "PERCENT",
  "BANG",
  "AND_AND",
  "OR_OR",
  "EQUAL_EQUAL",
  "BANG_EQUAL",
  "LESS",
  "LESS_EQUAL",
  "GREATER",
  "GREATER_EQUAL",
  "ASSIGN",
  "PLUS_ASSIGN",
  "MINUS_ASSIGN",
  "SHORT_DECL",
  "PLUS_PLUS",
  "MINUS_MINUS",
  "DOT",
  "COMMA",
  "SEMICOLON",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE"
  };
}

