
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.golite.parser;

import java_cup.runtime.*;
import com.golite.ast.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class GoLiteParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public GoLiteParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public GoLiteParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public GoLiteParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\012\000\002\002\004\000\002\002\005\000\002\002" +
    "\005\000\002\002\004\000\002\002\004\000\002\002\003" +
    "\000\002\002\003\000\002\002\003\000\002\002\003\000" +
    "\002\002\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\020\000\020\005\010\006\004\007\006\010\011\011" +
    "\005\012\007\013\012\001\002\000\020\005\010\006\004" +
    "\007\006\010\011\011\005\012\007\013\012\001\002\000" +
    "\010\002\ufffc\004\ufffc\005\ufffc\001\002\000\010\002\ufff9" +
    "\004\ufff9\005\ufff9\001\002\000\010\002\ufffb\004\ufffb\005" +
    "\ufffb\001\002\000\020\005\010\006\004\007\006\010\011" +
    "\011\005\012\007\013\012\001\002\000\010\002\ufff8\004" +
    "\ufff8\005\ufff8\001\002\000\010\002\ufffa\004\ufffa\005\ufffa" +
    "\001\002\000\010\002\016\004\014\005\015\001\002\000" +
    "\020\005\010\006\004\007\006\010\011\011\005\012\007" +
    "\013\012\001\002\000\020\005\010\006\004\007\006\010" +
    "\011\011\005\012\007\013\012\001\002\000\004\002\001" +
    "\001\002\000\010\002\uffff\004\uffff\005\uffff\001\002\000" +
    "\010\002\000\004\000\005\000\001\002\000\010\002\ufffe" +
    "\004\ufffe\005\ufffe\001\002\000\010\002\ufffd\004\ufffd\005" +
    "\ufffd\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\020\000\004\002\012\001\001\000\004\002\021\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\002\020\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\002\017\001\001\000\004" +
    "\002\016\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$GoLiteParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$GoLiteParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$GoLiteParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    // Este método se dispara automáticamente cuando hay un error sintáctico.
    // Más adelante conectaremos esto a tu tabla de errores de la interfaz gráfica.
    public void syntax_error(Symbol s) {
        System.out.println("Error Sintáctico en la Línea " + s.left + ", Columna " + s.right + ". No se esperaba: " + s.value);
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception {
        System.out.println("Error Sintáctico Irrecuperable.");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$GoLiteParser$actions {
  private final GoLiteParser parser;

  /** Constructor */
  CUP$GoLiteParser$actions(GoLiteParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$GoLiteParser$do_action_part00000000(
    int                        CUP$GoLiteParser$act_num,
    java_cup.runtime.lr_parser CUP$GoLiteParser$parser,
    java.util.Stack            CUP$GoLiteParser$stack,
    int                        CUP$GoLiteParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$GoLiteParser$result;

      /* select the action based on the action number */
      switch (CUP$GoLiteParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= expr EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).right;
		Expression start_val = (Expression)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).value;
		RESULT = start_val;
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$GoLiteParser$parser.done_parsing();
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // expr ::= expr PLUS expr 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new BinaryExpr(e1, "+", e2); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // expr ::= expr MINUS expr 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new BinaryExpr(e1, "-", e2); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // expr ::= MINUS expr 
            {
              Expression RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new UnaryExpr("-", e); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // expr ::= NOT expr 
            {
              Expression RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new UnaryExpr("!", e); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // expr ::= INT_LITERAL 
            {
              Expression RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Integer val = (Integer)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new LiteralExpr(val, LiteralExpr.Type.INT); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // expr ::= FLOAT_LITERAL 
            {
              Expression RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Double val = (Double)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new LiteralExpr(val, LiteralExpr.Type.FLOAT); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // expr ::= STRING_LITERAL 
            {
              Expression RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new LiteralExpr(val, LiteralExpr.Type.STRING); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expr ::= TRUE 
            {
              Expression RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Boolean val = (Boolean)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new LiteralExpr(val, LiteralExpr.Type.BOOL); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expr ::= FALSE 
            {
              Expression RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Boolean val = (Boolean)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new LiteralExpr(val, LiteralExpr.Type.BOOL); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$GoLiteParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$GoLiteParser$do_action(
    int                        CUP$GoLiteParser$act_num,
    java_cup.runtime.lr_parser CUP$GoLiteParser$parser,
    java.util.Stack            CUP$GoLiteParser$stack,
    int                        CUP$GoLiteParser$top)
    throws java.lang.Exception
    {
              return CUP$GoLiteParser$do_action_part00000000(
                               CUP$GoLiteParser$act_num,
                               CUP$GoLiteParser$parser,
                               CUP$GoLiteParser$stack,
                               CUP$GoLiteParser$top);
    }
}

}
