
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package com.golite.parser;

import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.List;
import com.golite.ast.*;
import com.golite.lexer.Token;
import com.golite.lexer.TokenType;
import com.golite.reports.ErrorType;
import com.golite.reports.ReportCollector;
import com.golite.runtime.Value;
import com.golite.runtime.ValueType;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150326 (SVN rev 63) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class GoLiteParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return GoLiteSym.class;
}

  /** Default constructor. */
  @Deprecated
  public GoLiteParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public GoLiteParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public GoLiteParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\117\000\002\002\004\000\002\002\003\000\002\002" +
    "\002\000\002\003\004\000\002\003\003\000\002\003\004" +
    "\000\002\003\005\000\002\004\004\000\002\004\004\000" +
    "\002\004\004\000\002\004\004\000\002\004\004\000\002" +
    "\004\003\000\002\004\003\000\002\004\003\000\002\004" +
    "\003\000\002\011\006\000\002\032\003\000\002\032\003" +
    "\000\002\032\003\000\002\032\003\000\002\032\003\000" +
    "\002\032\002\000\002\033\004\000\002\033\002\000\002" +
    "\012\005\000\002\007\007\000\002\007\007\000\002\007" +
    "\005\000\002\010\011\000\002\034\003\000\002\034\002" +
    "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
    "\002\006\005\000\002\006\004\000\002\006\005\000\002" +
    "\013\003\000\002\014\003\000\002\015\003\000\002\016" +
    "\005\000\002\016\003\000\002\017\005\000\002\017\003" +
    "\000\002\020\005\000\002\020\005\000\002\020\003\000" +
    "\002\021\005\000\002\021\005\000\002\021\005\000\002" +
    "\021\005\000\002\021\003\000\002\022\005\000\002\022" +
    "\005\000\002\022\003\000\002\023\005\000\002\023\005" +
    "\000\002\023\005\000\002\023\003\000\002\024\004\000" +
    "\002\024\004\000\002\024\003\000\002\025\005\000\002" +
    "\025\003\000\002\025\003\000\002\025\003\000\002\026" +
    "\006\000\002\026\010\000\002\031\005\000\002\031\003" +
    "\000\002\031\002\000\002\027\003\000\002\027\003\000" +
    "\002\027\003\000\002\027\003\000\002\027\003\000\002" +
    "\027\003\000\002\030\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\175\000\050\002\uffff\003\033\004\047\005\027\007" +
    "\017\010\035\011\012\017\053\020\051\021\045\022\006" +
    "\023\005\024\050\025\041\027\020\033\026\047\024\050" +
    "\011\052\040\001\002\000\004\002\177\001\002\000\044" +
    "\026\uffb6\027\uffb6\030\uffb6\031\uffb6\032\uffb6\034\uffb6\035" +
    "\uffb6\036\uffb6\037\uffb6\040\uffb6\041\uffb6\042\uffb6\043\uffb6" +
    "\046\uffb6\047\uffb6\051\uffb6\052\uffb6\001\002\000\044\026" +
    "\uffb7\027\uffb7\030\uffb7\031\uffb7\032\uffb7\034\uffb7\035\uffb7" +
    "\036\uffb7\037\uffb7\040\uffb7\041\uffb7\042\uffb7\043\uffb7\046" +
    "\uffb7\047\uffb7\051\uffb7\052\uffb7\001\002\000\004\047\176" +
    "\001\002\000\052\002\ufff4\003\ufff4\004\ufff4\005\ufff4\007" +
    "\ufff4\010\ufff4\011\ufff4\017\ufff4\020\ufff4\021\ufff4\022\ufff4" +
    "\023\ufff4\024\ufff4\025\ufff4\027\ufff4\033\ufff4\047\ufff4\050" +
    "\ufff4\052\ufff4\053\ufff4\001\002\000\026\017\062\020\051" +
    "\021\045\022\006\023\005\024\050\025\041\027\020\033" +
    "\026\050\011\001\002\000\004\047\uffda\001\002\000\044" +
    "\026\uffca\027\uffca\030\123\031\125\032\124\034\uffca\035" +
    "\uffca\036\uffca\037\uffca\040\uffca\041\uffca\042\uffca\043\uffca" +
    "\046\uffca\047\uffca\051\uffca\052\uffca\001\002\000\004\047" +
    "\173\001\002\000\052\002\ufff3\003\ufff3\004\ufff3\005\ufff3" +
    "\007\ufff3\010\ufff3\011\ufff3\017\ufff3\020\ufff3\021\ufff3\022" +
    "\ufff3\023\ufff3\024\ufff3\025\ufff3\027\ufff3\033\ufff3\047\ufff3" +
    "\050\ufff3\052\ufff3\053\ufff3\001\002\000\036\026\120\027" +
    "\121\034\uffcd\035\uffcd\036\uffcd\037\uffcd\040\uffcd\041\uffcd" +
    "\042\uffcd\043\uffcd\046\uffcd\047\uffcd\051\uffcd\052\uffcd\001" +
    "\002\000\032\004\047\017\053\020\051\021\045\022\006" +
    "\023\005\024\050\025\041\027\020\033\026\047\uffe2\050" +
    "\011\001\002\000\026\017\062\020\051\021\045\022\006" +
    "\023\005\024\050\025\041\027\020\033\026\050\011\001" +
    "\002\000\004\047\157\001\002\000\044\026\uffbf\027\uffbf" +
    "\030\uffbf\031\uffbf\032\uffbf\034\uffbf\035\uffbf\036\uffbf\037" +
    "\uffbf\040\uffbf\041\uffbf\042\uffbf\043\uffbf\046\uffbf\047\uffbf" +
    "\051\uffbf\052\uffbf\001\002\000\016\034\106\035\uffd7\046" +
    "\uffd7\047\uffd7\051\uffd7\052\uffd7\001\002\000\052\002\ufff2" +
    "\003\ufff2\004\ufff2\005\ufff2\007\ufff2\010\ufff2\011\ufff2\017" +
    "\ufff2\020\ufff2\021\ufff2\022\ufff2\023\ufff2\024\ufff2\025\ufff2" +
    "\027\ufff2\033\ufff2\047\ufff2\050\ufff2\052\ufff2\053\ufff2\001" +
    "\002\000\044\026\uffc6\027\uffc6\030\uffc6\031\uffc6\032\uffc6" +
    "\034\uffc6\035\uffc6\036\uffc6\037\uffc6\040\uffc6\041\uffc6\042" +
    "\uffc6\043\uffc6\046\uffc6\047\uffc6\051\uffc6\052\uffc6\001\002" +
    "\000\026\017\062\020\051\021\045\022\006\023\005\024" +
    "\050\025\041\027\020\033\026\050\011\001\002\000\026" +
    "\017\062\020\051\021\045\022\006\023\005\024\050\025" +
    "\041\027\020\033\026\050\011\001\002\000\004\047\150" +
    "\001\002\000\044\026\uffc3\027\uffc3\030\uffc3\031\uffc3\032" +
    "\uffc3\034\uffc3\035\uffc3\036\uffc3\037\uffc3\040\uffc3\041\uffc3" +
    "\042\uffc3\043\uffc3\046\uffc3\047\uffc3\051\uffc3\052\uffc3\001" +
    "\002\000\032\034\uffd2\035\uffd2\036\uffd2\037\uffd2\040\115" +
    "\041\116\042\113\043\114\046\uffd2\047\uffd2\051\uffd2\052" +
    "\uffd2\001\002\000\004\047\146\001\002\000\044\026\uffc0" +
    "\027\uffc0\030\uffc0\031\uffc0\032\uffc0\034\uffc0\035\uffc0\036" +
    "\uffc0\037\uffc0\040\uffc0\041\uffc0\042\uffc0\043\uffc0\046\uffc0" +
    "\047\uffc0\051\uffc0\052\uffc0\001\002\000\004\047\uffdb\001" +
    "\002\000\050\002\000\003\142\004\047\005\027\007\017" +
    "\010\035\011\012\017\053\020\051\021\045\022\006\023" +
    "\005\024\050\025\041\027\020\033\026\047\024\050\011" +
    "\052\040\001\002\000\022\034\uffd5\035\uffd5\036\111\037" +
    "\110\046\uffd5\047\uffd5\051\uffd5\052\uffd5\001\002\000\050" +
    "\003\137\004\047\005\027\007\017\010\035\011\012\017" +
    "\053\020\051\021\045\022\006\023\005\024\050\025\041" +
    "\027\020\033\026\047\024\050\011\052\040\053\141\001" +
    "\002\000\044\026\uffb4\027\uffb4\030\uffb4\031\uffb4\032\uffb4" +
    "\034\uffb4\035\uffb4\036\uffb4\037\uffb4\040\uffb4\041\uffb4\042" +
    "\uffb4\043\uffb4\046\uffb4\047\uffb4\051\uffb4\052\uffb4\001\002" +
    "\000\004\047\136\001\002\000\052\002\ufff5\003\ufff5\004" +
    "\ufff5\005\ufff5\007\ufff5\010\ufff5\011\ufff5\017\ufff5\020\ufff5" +
    "\021\ufff5\022\ufff5\023\ufff5\024\ufff5\025\ufff5\027\ufff5\033" +
    "\ufff5\047\ufff5\050\ufff5\052\ufff5\053\ufff5\001\002\000\044" +
    "\026\uffc1\027\uffc1\030\uffc1\031\uffc1\032\uffc1\034\uffc1\035" +
    "\uffc1\036\uffc1\037\uffc1\040\uffc1\041\uffc1\042\uffc1\043\uffc1" +
    "\046\uffc1\047\uffc1\051\uffc1\052\uffc1\001\002\000\044\026" +
    "\uffb8\027\uffb8\030\uffb8\031\uffb8\032\uffb8\034\uffb8\035\uffb8" +
    "\036\uffb8\037\uffb8\040\uffb8\041\uffb8\042\uffb8\043\uffb8\046" +
    "\uffb8\047\uffb8\051\uffb8\052\uffb8\001\002\000\014\035\104" +
    "\046\uffd9\047\uffd9\051\uffd9\052\uffd9\001\002\000\004\017" +
    "\072\001\002\000\044\026\uffb5\027\uffb5\030\uffb5\031\uffb5" +
    "\032\uffb5\034\uffb5\035\uffb5\036\uffb5\037\uffb5\040\uffb5\041" +
    "\uffb5\042\uffb5\043\uffb5\046\uffb5\047\uffb5\051\uffb5\052\uffb5" +
    "\001\002\000\044\026\uffb9\027\uffb9\030\uffb9\031\uffb9\032" +
    "\uffb9\034\uffb9\035\uffb9\036\uffb9\037\uffb9\040\uffb9\041\uffb9" +
    "\042\uffb9\043\uffb9\046\uffb9\047\uffb9\051\uffb9\052\uffb9\001" +
    "\002\000\052\002\ufffd\003\ufffd\004\ufffd\005\ufffd\007\ufffd" +
    "\010\ufffd\011\ufffd\017\ufffd\020\ufffd\021\ufffd\022\ufffd\023" +
    "\ufffd\024\ufffd\025\ufffd\027\ufffd\033\ufffd\047\ufffd\050\ufffd" +
    "\052\ufffd\053\ufffd\001\002\000\046\026\uffb3\027\uffb3\030" +
    "\uffb3\031\uffb3\032\uffb3\034\uffb3\035\uffb3\036\uffb3\037\uffb3" +
    "\040\uffb3\041\uffb3\042\uffb3\043\uffb3\044\055\045\056\047" +
    "\uffb3\050\054\052\uffb3\001\002\000\032\017\062\020\051" +
    "\021\045\022\006\023\005\024\050\025\041\027\020\033" +
    "\026\046\uffba\050\011\051\uffba\001\002\000\026\017\062" +
    "\020\051\021\045\022\006\023\005\024\050\025\041\027" +
    "\020\033\026\050\011\001\002\000\004\017\057\001\002" +
    "\000\004\050\060\001\002\000\032\017\062\020\051\021" +
    "\045\022\006\023\005\024\050\025\041\027\020\033\026" +
    "\046\uffba\050\011\051\uffba\001\002\000\006\046\uffbb\051" +
    "\uffbb\001\002\000\050\026\uffb3\027\uffb3\030\uffb3\031\uffb3" +
    "\032\uffb3\034\uffb3\035\uffb3\036\uffb3\037\uffb3\040\uffb3\041" +
    "\uffb3\042\uffb3\043\uffb3\045\056\046\uffb3\047\uffb3\050\054" +
    "\051\uffb3\052\uffb3\001\002\000\006\046\064\051\065\001" +
    "\002\000\026\017\062\020\051\021\045\022\006\023\005" +
    "\024\050\025\041\027\020\033\026\050\011\001\002\000" +
    "\044\026\uffbd\027\uffbd\030\uffbd\031\uffbd\032\uffbd\034\uffbd" +
    "\035\uffbd\036\uffbd\037\uffbd\040\uffbd\041\uffbd\042\uffbd\043" +
    "\uffbd\046\uffbd\047\uffbd\051\uffbd\052\uffbd\001\002\000\006" +
    "\046\uffbc\051\uffbc\001\002\000\006\047\uffe8\052\uffe8\001" +
    "\002\000\006\046\064\051\071\001\002\000\044\026\uffbe" +
    "\027\uffbe\030\uffbe\031\uffbe\032\uffbe\034\uffbe\035\uffbe\036" +
    "\uffbe\037\uffbe\040\uffbe\041\uffbe\042\uffbe\043\uffbe\046\uffbe" +
    "\047\uffbe\051\uffbe\052\uffbe\001\002\000\022\012\075\013" +
    "\100\014\076\015\073\016\074\044\uffeb\047\uffeb\052\uffeb" +
    "\001\002\000\010\044\uffee\047\uffee\052\uffee\001\002\000" +
    "\010\044\uffec\047\uffec\052\uffec\001\002\000\010\044\ufff0" +
    "\047\ufff0\052\ufff0\001\002\000\010\044\uffed\047\uffed\052" +
    "\uffed\001\002\000\010\044\102\047\uffe9\052\uffe9\001\002" +
    "\000\010\044\uffef\047\uffef\052\uffef\001\002\000\006\047" +
    "\ufff1\052\ufff1\001\002\000\026\017\062\020\051\021\045" +
    "\022\006\023\005\024\050\025\041\027\020\033\026\050" +
    "\011\001\002\000\006\047\uffea\052\uffea\001\002\000\026" +
    "\017\062\020\051\021\045\022\006\023\005\024\050\025" +
    "\041\027\020\033\026\050\011\001\002\000\016\034\106" +
    "\035\uffd8\046\uffd8\047\uffd8\051\uffd8\052\uffd8\001\002\000" +
    "\026\017\062\020\051\021\045\022\006\023\005\024\050" +
    "\025\041\027\020\033\026\050\011\001\002\000\022\034" +
    "\uffd6\035\uffd6\036\111\037\110\046\uffd6\047\uffd6\051\uffd6" +
    "\052\uffd6\001\002\000\026\017\062\020\051\021\045\022" +
    "\006\023\005\024\050\025\041\027\020\033\026\050\011" +
    "\001\002\000\026\017\062\020\051\021\045\022\006\023" +
    "\005\024\050\025\041\027\020\033\026\050\011\001\002" +
    "\000\032\034\uffd4\035\uffd4\036\uffd4\037\uffd4\040\115\041" +
    "\116\042\113\043\114\046\uffd4\047\uffd4\051\uffd4\052\uffd4" +
    "\001\002\000\026\017\062\020\051\021\045\022\006\023" +
    "\005\024\050\025\041\027\020\033\026\050\011\001\002" +
    "\000\026\017\062\020\051\021\045\022\006\023\005\024" +
    "\050\025\041\027\020\033\026\050\011\001\002\000\026" +
    "\017\062\020\051\021\045\022\006\023\005\024\050\025" +
    "\041\027\020\033\026\050\011\001\002\000\026\017\062" +
    "\020\051\021\045\022\006\023\005\024\050\025\041\027" +
    "\020\033\026\050\011\001\002\000\036\026\120\027\121" +
    "\034\uffd0\035\uffd0\036\uffd0\037\uffd0\040\uffd0\041\uffd0\042" +
    "\uffd0\043\uffd0\046\uffd0\047\uffd0\051\uffd0\052\uffd0\001\002" +
    "\000\026\017\062\020\051\021\045\022\006\023\005\024" +
    "\050\025\041\027\020\033\026\050\011\001\002\000\026" +
    "\017\062\020\051\021\045\022\006\023\005\024\050\025" +
    "\041\027\020\033\026\050\011\001\002\000\044\026\uffcb" +
    "\027\uffcb\030\123\031\125\032\124\034\uffcb\035\uffcb\036" +
    "\uffcb\037\uffcb\040\uffcb\041\uffcb\042\uffcb\043\uffcb\046\uffcb" +
    "\047\uffcb\051\uffcb\052\uffcb\001\002\000\026\017\062\020" +
    "\051\021\045\022\006\023\005\024\050\025\041\027\020" +
    "\033\026\050\011\001\002\000\026\017\062\020\051\021" +
    "\045\022\006\023\005\024\050\025\041\027\020\033\026" +
    "\050\011\001\002\000\026\017\062\020\051\021\045\022" +
    "\006\023\005\024\050\025\041\027\020\033\026\050\011" +
    "\001\002\000\044\026\uffc8\027\uffc8\030\uffc8\031\uffc8\032" +
    "\uffc8\034\uffc8\035\uffc8\036\uffc8\037\uffc8\040\uffc8\041\uffc8" +
    "\042\uffc8\043\uffc8\046\uffc8\047\uffc8\051\uffc8\052\uffc8\001" +
    "\002\000\044\026\uffc7\027\uffc7\030\uffc7\031\uffc7\032\uffc7" +
    "\034\uffc7\035\uffc7\036\uffc7\037\uffc7\040\uffc7\041\uffc7\042" +
    "\uffc7\043\uffc7\046\uffc7\047\uffc7\051\uffc7\052\uffc7\001\002" +
    "\000\044\026\uffc9\027\uffc9\030\uffc9\031\uffc9\032\uffc9\034" +
    "\uffc9\035\uffc9\036\uffc9\037\uffc9\040\uffc9\041\uffc9\042\uffc9" +
    "\043\uffc9\046\uffc9\047\uffc9\051\uffc9\052\uffc9\001\002\000" +
    "\044\026\uffcc\027\uffcc\030\123\031\125\032\124\034\uffcc" +
    "\035\uffcc\036\uffcc\037\uffcc\040\uffcc\041\uffcc\042\uffcc\043" +
    "\uffcc\046\uffcc\047\uffcc\051\uffcc\052\uffcc\001\002\000\036" +
    "\026\120\027\121\034\uffd1\035\uffd1\036\uffd1\037\uffd1\040" +
    "\uffd1\041\uffd1\042\uffd1\043\uffd1\046\uffd1\047\uffd1\051\uffd1" +
    "\052\uffd1\001\002\000\036\026\120\027\121\034\uffce\035" +
    "\uffce\036\uffce\037\uffce\040\uffce\041\uffce\042\uffce\043\uffce" +
    "\046\uffce\047\uffce\051\uffce\052\uffce\001\002\000\036\026" +
    "\120\027\121\034\uffcf\035\uffcf\036\uffcf\037\uffcf\040\uffcf" +
    "\041\uffcf\042\uffcf\043\uffcf\046\uffcf\047\uffcf\051\uffcf\052" +
    "\uffcf\001\002\000\032\034\uffd3\035\uffd3\036\uffd3\037\uffd3" +
    "\040\115\041\116\042\113\043\114\046\uffd3\047\uffd3\051" +
    "\uffd3\052\uffd3\001\002\000\052\002\ufff6\003\ufff6\004\ufff6" +
    "\005\ufff6\007\ufff6\010\ufff6\011\ufff6\017\ufff6\020\ufff6\021" +
    "\ufff6\022\ufff6\023\ufff6\024\ufff6\025\ufff6\027\ufff6\033\ufff6" +
    "\047\ufff6\050\ufff6\052\ufff6\053\ufff6\001\002\000\006\047" +
    "\146\053\147\001\002\000\050\003\142\004\047\005\027" +
    "\007\017\010\035\011\012\017\053\020\051\021\045\022" +
    "\006\023\005\024\050\025\041\027\020\033\026\047\024" +
    "\050\011\052\040\053\143\001\002\000\054\002\uffdd\003" +
    "\uffdd\004\uffdd\005\uffdd\006\uffdd\007\uffdd\010\uffdd\011\uffdd" +
    "\017\uffdd\020\uffdd\021\uffdd\022\uffdd\023\uffdd\024\uffdd\025" +
    "\uffdd\027\uffdd\033\uffdd\047\uffdd\050\uffdd\052\uffdd\053\uffdd" +
    "\001\002\000\004\047\145\001\002\000\054\002\uffde\003" +
    "\uffde\004\uffde\005\uffde\006\uffde\007\uffde\010\uffde\011\uffde" +
    "\017\uffde\020\uffde\021\uffde\022\uffde\023\uffde\024\uffde\025" +
    "\uffde\027\uffde\033\uffde\047\uffde\050\uffde\052\uffde\053\uffde" +
    "\001\002\000\052\002\ufffe\003\ufffe\004\ufffe\005\ufffe\007" +
    "\ufffe\010\ufffe\011\ufffe\017\ufffe\020\ufffe\021\ufffe\022\ufffe" +
    "\023\ufffe\024\ufffe\025\ufffe\027\ufffe\033\ufffe\047\ufffe\050" +
    "\ufffe\052\ufffe\053\ufffe\001\002\000\052\002\ufffb\003\ufffb" +
    "\004\ufffb\005\ufffb\007\ufffb\010\ufffb\011\ufffb\017\ufffb\020" +
    "\ufffb\021\ufffb\022\ufffb\023\ufffb\024\ufffb\025\ufffb\027\ufffb" +
    "\033\ufffb\047\ufffb\050\ufffb\052\ufffb\053\ufffb\001\002\000" +
    "\052\002\ufffc\003\ufffc\004\ufffc\005\ufffc\007\ufffc\010\ufffc" +
    "\011\ufffc\017\ufffc\020\ufffc\021\ufffc\022\ufffc\023\ufffc\024" +
    "\ufffc\025\ufffc\027\ufffc\033\ufffc\047\ufffc\050\ufffc\052\ufffc" +
    "\053\ufffc\001\002\000\054\002\uffdc\003\uffdc\004\uffdc\005" +
    "\uffdc\006\uffdc\007\uffdc\010\uffdc\011\uffdc\017\uffdc\020\uffdc" +
    "\021\uffdc\022\uffdc\023\uffdc\024\uffdc\025\uffdc\027\uffdc\033" +
    "\uffdc\047\uffdc\050\uffdc\052\uffdc\053\uffdc\001\002\000\052" +
    "\002\ufff9\003\ufff9\004\ufff9\005\ufff9\007\ufff9\010\ufff9\011" +
    "\ufff9\017\ufff9\020\ufff9\021\ufff9\022\ufff9\023\ufff9\024\ufff9" +
    "\025\ufff9\027\ufff9\033\ufff9\047\ufff9\050\ufff9\052\ufff9\053" +
    "\ufff9\001\002\000\004\052\040\001\002\000\054\002\uffe5" +
    "\003\uffe5\004\uffe5\005\uffe5\006\153\007\uffe5\010\uffe5\011" +
    "\uffe5\017\uffe5\020\uffe5\021\uffe5\022\uffe5\023\uffe5\024\uffe5" +
    "\025\uffe5\027\uffe5\033\uffe5\047\uffe5\050\uffe5\052\uffe5\053" +
    "\uffe5\001\002\000\006\005\027\052\040\001\002\000\052" +
    "\002\uffe7\003\uffe7\004\uffe7\005\uffe7\007\uffe7\010\uffe7\011" +
    "\uffe7\017\uffe7\020\uffe7\021\uffe7\022\uffe7\023\uffe7\024\uffe7" +
    "\025\uffe7\027\uffe7\033\uffe7\047\uffe7\050\uffe7\052\uffe7\053" +
    "\uffe7\001\002\000\052\002\uffe6\003\uffe6\004\uffe6\005\uffe6" +
    "\007\uffe6\010\uffe6\011\uffe6\017\uffe6\020\uffe6\021\uffe6\022" +
    "\uffe6\023\uffe6\024\uffe6\025\uffe6\027\uffe6\033\uffe6\047\uffe6" +
    "\050\uffe6\052\uffe6\053\uffe6\001\002\000\044\026\uffc5\027" +
    "\uffc5\030\uffc5\031\uffc5\032\uffc5\034\uffc5\035\uffc5\036\uffc5" +
    "\037\uffc5\040\uffc5\041\uffc5\042\uffc5\043\uffc5\046\uffc5\047" +
    "\uffc5\051\uffc5\052\uffc5\001\002\000\052\002\ufff8\003\ufff8" +
    "\004\ufff8\005\ufff8\007\ufff8\010\ufff8\011\ufff8\017\ufff8\020" +
    "\ufff8\021\ufff8\022\ufff8\023\ufff8\024\ufff8\025\ufff8\027\ufff8" +
    "\033\ufff8\047\ufff8\050\ufff8\052\ufff8\053\ufff8\001\002\000" +
    "\044\026\uffc4\027\uffc4\030\uffc4\031\uffc4\032\uffc4\034\uffc4" +
    "\035\uffc4\036\uffc4\037\uffc4\040\uffc4\041\uffc4\042\uffc4\043" +
    "\uffc4\046\uffc4\047\uffc4\051\uffc4\052\uffc4\001\002\000\006" +
    "\047\uffdf\052\uffdf\001\002\000\006\047\uffe3\052\uffe3\001" +
    "\002\000\004\047\166\001\002\000\006\047\uffe0\052\uffe0" +
    "\001\002\000\006\047\uffe1\052\uffe1\001\002\000\006\044" +
    "\102\047\uffe9\001\002\000\004\047\170\001\002\000\032" +
    "\004\047\017\053\020\051\021\045\022\006\023\005\024" +
    "\050\025\041\027\020\033\026\050\011\052\uffe2\001\002" +
    "\000\004\052\040\001\002\000\052\002\uffe4\003\uffe4\004" +
    "\uffe4\005\uffe4\007\uffe4\010\uffe4\011\uffe4\017\uffe4\020\uffe4" +
    "\021\uffe4\022\uffe4\023\uffe4\024\uffe4\025\uffe4\027\uffe4\033" +
    "\uffe4\047\uffe4\050\uffe4\052\uffe4\053\uffe4\001\002\000\052" +
    "\002\ufffa\003\ufffa\004\ufffa\005\ufffa\007\ufffa\010\ufffa\011" +
    "\ufffa\017\ufffa\020\ufffa\021\ufffa\022\ufffa\023\ufffa\024\ufffa" +
    "\025\ufffa\027\ufffa\033\ufffa\047\ufffa\050\ufffa\052\ufffa\053" +
    "\ufffa\001\002\000\004\051\175\001\002\000\044\026\uffc2" +
    "\027\uffc2\030\uffc2\031\uffc2\032\uffc2\034\uffc2\035\uffc2\036" +
    "\uffc2\037\uffc2\040\uffc2\041\uffc2\042\uffc2\043\uffc2\046\uffc2" +
    "\047\uffc2\051\uffc2\052\uffc2\001\002\000\052\002\ufff7\003" +
    "\ufff7\004\ufff7\005\ufff7\007\ufff7\010\ufff7\011\ufff7\017\ufff7" +
    "\020\ufff7\021\ufff7\022\ufff7\023\ufff7\024\ufff7\025\ufff7\027" +
    "\ufff7\033\ufff7\047\ufff7\050\ufff7\052\ufff7\053\ufff7\001\002" +
    "\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\175\000\056\002\003\003\035\004\051\006\014\007" +
    "\042\010\007\011\013\012\027\013\020\014\006\015\041" +
    "\016\045\017\022\020\036\021\031\022\015\023\012\024" +
    "\024\025\030\026\033\027\043\030\021\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\032\015\173\016\045\017\022" +
    "\020\036\021\031\022\015\023\012\024\024\025\030\026" +
    "\033\027\043\030\021\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\042\005\161\011\163\012\164\015\160\016\045" +
    "\017\022\020\036\021\031\022\015\023\012\024\024\025" +
    "\030\026\033\027\043\030\021\034\162\001\001\000\014" +
    "\024\157\025\030\026\033\027\043\030\021\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\024\155\025\030\026" +
    "\033\027\043\030\021\001\001\000\032\015\150\016\045" +
    "\017\022\020\036\021\031\022\015\023\012\024\024\025" +
    "\030\026\033\027\043\030\021\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\052\004\143\006\014" +
    "\007\042\010\007\011\013\012\027\013\020\014\006\015" +
    "\041\016\045\017\022\020\036\021\031\022\015\023\012" +
    "\024\024\025\030\026\033\027\043\030\021\001\001\000" +
    "\002\001\001\000\054\003\137\004\051\006\014\007\042" +
    "\010\007\011\013\012\027\013\020\014\006\015\041\016" +
    "\045\017\022\020\036\021\031\022\015\023\012\024\024" +
    "\025\030\026\033\027\043\030\021\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\034\015\060\016\045\017\022\020\036\021" +
    "\031\022\015\023\012\024\024\025\030\026\033\027\043" +
    "\030\021\031\067\001\001\000\032\015\066\016\045\017" +
    "\022\020\036\021\031\022\015\023\012\024\024\025\030" +
    "\026\033\027\043\030\021\001\001\000\002\001\001\000" +
    "\002\001\001\000\034\015\060\016\045\017\022\020\036" +
    "\021\031\022\015\023\012\024\024\025\030\026\033\027" +
    "\043\030\021\031\062\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\032\015\065\016\045\017" +
    "\022\020\036\021\031\022\015\023\012\024\024\025\030" +
    "\026\033\027\043\030\021\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\032\076\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\033\100\001\001\000\002\001\001\000\002\001\001\000" +
    "\032\015\102\016\045\017\022\020\036\021\031\022\015" +
    "\023\012\024\024\025\030\026\033\027\043\030\021\001" +
    "\001\000\002\001\001\000\026\017\104\020\036\021\031" +
    "\022\015\023\012\024\024\025\030\026\033\027\043\030" +
    "\021\001\001\000\002\001\001\000\024\020\106\021\031" +
    "\022\015\023\012\024\024\025\030\026\033\027\043\030" +
    "\021\001\001\000\002\001\001\000\022\021\134\022\015" +
    "\023\012\024\024\025\030\026\033\027\043\030\021\001" +
    "\001\000\022\021\111\022\015\023\012\024\024\025\030" +
    "\026\033\027\043\030\021\001\001\000\002\001\001\000" +
    "\020\022\133\023\012\024\024\025\030\026\033\027\043" +
    "\030\021\001\001\000\020\022\132\023\012\024\024\025" +
    "\030\026\033\027\043\030\021\001\001\000\020\022\131" +
    "\023\012\024\024\025\030\026\033\027\043\030\021\001" +
    "\001\000\020\022\116\023\012\024\024\025\030\026\033" +
    "\027\043\030\021\001\001\000\002\001\001\000\016\023" +
    "\130\024\024\025\030\026\033\027\043\030\021\001\001" +
    "\000\016\023\121\024\024\025\030\026\033\027\043\030" +
    "\021\001\001\000\002\001\001\000\014\024\127\025\030" +
    "\026\033\027\043\030\021\001\001\000\014\024\126\025" +
    "\030\026\033\027\043\030\021\001\001\000\014\024\125" +
    "\025\030\026\033\027\043\030\021\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\052" +
    "\004\143\006\014\007\042\010\007\011\013\012\027\013" +
    "\020\014\006\015\041\016\045\017\022\020\036\021\031" +
    "\022\015\023\012\024\024\025\030\026\033\027\043\030" +
    "\021\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\006\151" +
    "\001\001\000\002\001\001\000\006\006\154\007\153\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\033\166\001\001\000\002\001\001\000" +
    "\042\005\161\011\163\012\164\015\160\016\045\017\022" +
    "\020\036\021\031\022\015\023\012\024\024\025\030\026" +
    "\033\027\043\030\021\034\170\001\001\000\004\006\171" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$GoLiteParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$GoLiteParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$GoLiteParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 
    return ((java_cup.runtime.Scanner) getScanner()).next_token();

    }

 
    private final ReportCollector reportCollector;

    public GoLiteParser(java_cup.runtime.Scanner scanner, ReportCollector reportCollector) {
        super(scanner);
        this.reportCollector = reportCollector;
    }

    public void syntax_error(java_cup.runtime.Symbol current) {
        int line = -1;
        int column = -1;
        if (current != null && current.value instanceof Token) {
            Token token = (Token) current.value;
            line = token.line();
            column = token.column();
        }
        reportCollector.addError(ErrorType.SYNTACTIC, line, column, "se encontro una instruccion que no cuadra con la gramatica");
    }

    public void unrecovered_syntax_error(java_cup.runtime.Symbol current) throws java.lang.Exception {
        int line = -1;
        int column = -1;
        if (current != null && current.value instanceof Token) {
            Token token = (Token) current.value;
            line = token.line();
            column = token.column();
        }
        reportCollector.addError(ErrorType.SYNTACTIC, line, column, "el parser ya no pudo recuperarse de este error");
    }

    private List<Stmt> appendStmt(List<Stmt> list, Stmt stmt) {
        List<Stmt> result = list == null ? new ArrayList<>() : new ArrayList<>(list);
        if (stmt != null) {
            result.add(stmt);
        }
        return result;
    }

    private Value buildLiteral(Token token) {
        switch (token.type()) {
            case INT_LITERAL: return Value.ofInt(((Number) token.literal()).longValue());
            case FLOAT_LITERAL: return Value.ofFloat(((Number) token.literal()).doubleValue());
            case STRING_LITERAL: return Value.ofString(token.literal().toString());
            case RUNE_LITERAL: return Value.ofRune((Integer) token.literal());
            case BOOL_LITERAL: return Value.bool(Boolean.TRUE.equals(token.literal()));
            case NIL_LITERAL: return Value.nil();
            default: return Value.voidValue();
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$GoLiteParser$actions {
  private final GoLiteParser parser;

  /** Constructor */
  CUP$GoLiteParser$actions(GoLiteParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$GoLiteParser$do_action_part00000000(
    int                        CUP$GoLiteParser$act_num,
    java_cup.runtime.lr_parser CUP$GoLiteParser$parser,
    java.util.Stack            CUP$GoLiteParser$stack,
    int                        CUP$GoLiteParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$GoLiteParser$result;

      /* select the action based on the action number */
      switch (CUP$GoLiteParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).right;
		Program start_val = (Program)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).value;
		RESULT = start_val;
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$GoLiteParser$parser.done_parsing();
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= stmt_list 
            {
              Program RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		List s = (List)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new Program(s == null ? new ArrayList<>() : s); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= 
            {
              Program RESULT =null;
		 RESULT = new Program(new ArrayList<>()); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // stmt_list ::= stmt_list stmt 
            {
              List RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).right;
		List s = (List)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Stmt t = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = appendStmt(s, t); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("stmt_list",1, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // stmt_list ::= stmt 
            {
              List RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Stmt t = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 List<Stmt> list = new ArrayList<>(); list.add(t); RESULT = list; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("stmt_list",1, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // stmt_list ::= error SEMICOLON 
            {
              List RESULT =null;
		 RESULT = new ArrayList<>(); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("stmt_list",1, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // stmt_list ::= stmt_list error SEMICOLON 
            {
              List RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		List s = (List)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		 RESULT = s; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("stmt_list",1, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // stmt ::= var_decl SEMICOLON 
            {
              Stmt RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).right;
		Stmt v = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).value;
		 RESULT = v; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // stmt ::= assign_stmt SEMICOLON 
            {
              Stmt RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).right;
		Stmt a = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).value;
		 RESULT = a; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // stmt ::= break_stmt SEMICOLON 
            {
              Stmt RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).right;
		Stmt b = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).value;
		 RESULT = b; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // stmt ::= continue_stmt SEMICOLON 
            {
              Stmt RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).right;
		Stmt c = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).value;
		 RESULT = c; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // stmt ::= expr SEMICOLON 
            {
              Stmt RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).value;
		 RESULT = new ExpressionStmt(e); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // stmt ::= if_stmt 
            {
              Stmt RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Stmt i = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = i; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // stmt ::= for_stmt 
            {
              Stmt RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Stmt f = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = f; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // stmt ::= block 
            {
              Stmt RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Stmt b = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = b; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // stmt ::= SEMICOLON 
            {
              Stmt RESULT =null;
		 RESULT = null; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // var_decl ::= VAR IDENTIFIER opt_type opt_expr 
            {
              Stmt RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).right;
		ValueType t = (ValueType)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new VarDeclStmt(id.lexeme(), t, e); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("var_decl",7, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-3)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // opt_type ::= TYPE_INT 
            {
              ValueType RESULT =null;
		 RESULT = ValueType.INT; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("opt_type",24, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // opt_type ::= TYPE_FLOAT64 
            {
              ValueType RESULT =null;
		 RESULT = ValueType.FLOAT; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("opt_type",24, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // opt_type ::= TYPE_STRING 
            {
              ValueType RESULT =null;
		 RESULT = ValueType.STRING; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("opt_type",24, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // opt_type ::= TYPE_BOOL 
            {
              ValueType RESULT =null;
		 RESULT = ValueType.BOOL; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("opt_type",24, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // opt_type ::= TYPE_RUNE 
            {
              ValueType RESULT =null;
		 RESULT = ValueType.RUNE; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("opt_type",24, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // opt_type ::= 
            {
              ValueType RESULT =null;
		 RESULT = null; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("opt_type",24, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // opt_expr ::= ASSIGN expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = e; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("opt_expr",25, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // opt_expr ::= 
            {
              Expr RESULT =null;
		 RESULT = null; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("opt_expr",25, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // assign_stmt ::= IDENTIFIER ASSIGN expr 
            {
              Stmt RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new ExpressionStmt(new AssignmentExpr(id.lexeme(), e)); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("assign_stmt",8, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // if_stmt ::= IF expr block ELSE if_stmt 
            {
              Stmt RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-3)).right;
		Expr c = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Stmt t = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Stmt e = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new IfStmt(c, t, e); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("if_stmt",5, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-4)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // if_stmt ::= IF expr block ELSE block 
            {
              Stmt RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-3)).right;
		Expr c = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Stmt t = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Stmt e = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new IfStmt(c, t, e); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("if_stmt",5, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-4)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // if_stmt ::= IF expr block 
            {
              Stmt RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).right;
		Expr c = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Stmt t = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new IfStmt(c, t, null); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("if_stmt",5, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // for_stmt ::= FOR opt_simple_stmt SEMICOLON opt_expr SEMICOLON opt_simple_stmt block 
            {
              Stmt RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-5)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-5)).right;
		Stmt i = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-5)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-3)).right;
		Expr c = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-3)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).right;
		Stmt p = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Stmt b = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new ForStmt(i, c, p, b); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("for_stmt",6, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-6)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // opt_simple_stmt ::= simple_stmt 
            {
              Stmt RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Stmt s = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = s; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("opt_simple_stmt",26, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // opt_simple_stmt ::= 
            {
              Stmt RESULT =null;
		 RESULT = null; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("opt_simple_stmt",26, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // simple_stmt ::= assign_stmt 
            {
              Stmt RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Stmt a = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = a; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("simple_stmt",3, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // simple_stmt ::= var_decl 
            {
              Stmt RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Stmt v = (Stmt)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = v; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("simple_stmt",3, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // simple_stmt ::= expr 
            {
              Stmt RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new ExpressionStmt(e); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("simple_stmt",3, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // block ::= LBRACE stmt_list RBRACE 
            {
              Stmt RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).right;
		List s = (List)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).value;
		 RESULT = new BlockStmt(s == null ? new ArrayList<>() : s); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("block",4, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // block ::= LBRACE RBRACE 
            {
              Stmt RESULT =null;
		 RESULT = new BlockStmt(new ArrayList<>()); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("block",4, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // block ::= LBRACE error RBRACE 
            {
              Stmt RESULT =null;
		 RESULT = new BlockStmt(new ArrayList<>()); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("block",4, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // break_stmt ::= BREAK 
            {
              Stmt RESULT =null;
		 RESULT = new BreakStmt(); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("break_stmt",9, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // continue_stmt ::= CONTINUE 
            {
              Stmt RESULT =null;
		 RESULT = new ContinueStmt(); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("continue_stmt",10, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr ::= or_expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = e; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // or_expr ::= or_expr OR_OR and_expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new BinaryExpr(l, TokenType.OR_OR, r); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("or_expr",12, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // or_expr ::= and_expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = e; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("or_expr",12, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // and_expr ::= and_expr AND_AND equality_expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new BinaryExpr(l, TokenType.AND_AND, r); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("and_expr",13, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // and_expr ::= equality_expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = e; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("and_expr",13, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // equality_expr ::= equality_expr EQUAL_EQUAL relational_expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new BinaryExpr(l, TokenType.EQUAL_EQUAL, r); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("equality_expr",14, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // equality_expr ::= equality_expr BANG_EQUAL relational_expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new BinaryExpr(l, TokenType.BANG_EQUAL, r); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("equality_expr",14, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // equality_expr ::= relational_expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = e; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("equality_expr",14, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // relational_expr ::= relational_expr LESS additive_expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new BinaryExpr(l, TokenType.LESS, r); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("relational_expr",15, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // relational_expr ::= relational_expr LESS_EQUAL additive_expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new BinaryExpr(l, TokenType.LESS_EQUAL, r); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("relational_expr",15, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // relational_expr ::= relational_expr GREATER additive_expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new BinaryExpr(l, TokenType.GREATER, r); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("relational_expr",15, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // relational_expr ::= relational_expr GREATER_EQUAL additive_expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new BinaryExpr(l, TokenType.GREATER_EQUAL, r); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("relational_expr",15, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // relational_expr ::= additive_expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = e; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("relational_expr",15, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // additive_expr ::= additive_expr PLUS multiplicative_expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new BinaryExpr(l, TokenType.PLUS, r); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("additive_expr",16, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // additive_expr ::= additive_expr MINUS multiplicative_expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new BinaryExpr(l, TokenType.MINUS, r); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("additive_expr",16, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // additive_expr ::= multiplicative_expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = e; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("additive_expr",16, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // multiplicative_expr ::= multiplicative_expr STAR unary_expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new BinaryExpr(l, TokenType.STAR, r); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("multiplicative_expr",17, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // multiplicative_expr ::= multiplicative_expr SLASH unary_expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new BinaryExpr(l, TokenType.SLASH, r); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("multiplicative_expr",17, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // multiplicative_expr ::= multiplicative_expr PERCENT unary_expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr r = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new BinaryExpr(l, TokenType.PERCENT, r); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("multiplicative_expr",17, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // multiplicative_expr ::= unary_expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = e; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("multiplicative_expr",17, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // unary_expr ::= BANG unary_expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new UnaryExpr(TokenType.BANG, e); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("unary_expr",18, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // unary_expr ::= MINUS unary_expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new UnaryExpr(TokenType.MINUS, e); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("unary_expr",18, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // unary_expr ::= primary_expr 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = e; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("unary_expr",18, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // primary_expr ::= LPAREN expr RPAREN 
            {
              Expr RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).value;
		 RESULT = new GroupingExpr(e); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("primary_expr",19, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // primary_expr ::= literal_expr 
            {
              Expr RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr l = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = l; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("primary_expr",19, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // primary_expr ::= call_expr 
            {
              Expr RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr c = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = c; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("primary_expr",19, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // primary_expr ::= ident_expr 
            {
              Expr RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr i = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = i; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("primary_expr",19, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // call_expr ::= IDENTIFIER LPAREN arg_list RPAREN 
            {
              Expr RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-3)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-3)).value;
		int argsleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).right;
		List args = (List)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).value;
		 RESULT = new CallExpr(id.lexeme(), args == null ? new ArrayList<>() : args); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("call_expr",20, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-3)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // call_expr ::= IDENTIFIER DOT IDENTIFIER LPAREN arg_list RPAREN 
            {
              Expr RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-5)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-5)).value;
		int memberleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-3)).left;
		int memberright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-3)).right;
		Token member = (Token)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-3)).value;
		int argsleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).right;
		List args = (List)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-1)).value;
		 RESULT = new CallExpr(id.lexeme() + "." + member.lexeme(), args == null ? new ArrayList<>() : args); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("call_expr",20, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-5)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // arg_list ::= arg_list COMMA expr 
            {
              List RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).right;
		List l = (List)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 List<Expr> result = l == null ? new ArrayList<>() : new ArrayList<>(l); result.add(e); RESULT = result; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("arg_list",23, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.elementAt(CUP$GoLiteParser$top-2)), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // arg_list ::= expr 
            {
              List RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 List<Expr> result = new ArrayList<>(); result.add(e); RESULT = result; 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("arg_list",23, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // arg_list ::= 
            {
              List RESULT =null;
		 RESULT = new ArrayList<>(); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("arg_list",23, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // literal_expr ::= INT_LITERAL 
            {
              Expr RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Token t = (Token)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new LiteralExpr(buildLiteral(t)); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("literal_expr",21, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // literal_expr ::= FLOAT_LITERAL 
            {
              Expr RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Token t = (Token)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new LiteralExpr(buildLiteral(t)); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("literal_expr",21, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // literal_expr ::= STRING_LITERAL 
            {
              Expr RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Token t = (Token)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new LiteralExpr(buildLiteral(t)); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("literal_expr",21, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // literal_expr ::= RUNE_LITERAL 
            {
              Expr RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Token t = (Token)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new LiteralExpr(buildLiteral(t)); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("literal_expr",21, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // literal_expr ::= BOOL_LITERAL 
            {
              Expr RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Token t = (Token)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new LiteralExpr(buildLiteral(t)); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("literal_expr",21, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // literal_expr ::= NIL_LITERAL 
            {
              Expr RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Token t = (Token)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new LiteralExpr(buildLiteral(t)); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("literal_expr",21, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // ident_expr ::= IDENTIFIER 
            {
              Expr RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$GoLiteParser$stack.peek()).value;
		 RESULT = new VariableExpr(id.lexeme()); 
              CUP$GoLiteParser$result = parser.getSymbolFactory().newSymbol("ident_expr",22, ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$GoLiteParser$stack.peek()), RESULT);
            }
          return CUP$GoLiteParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$GoLiteParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$GoLiteParser$do_action(
    int                        CUP$GoLiteParser$act_num,
    java_cup.runtime.lr_parser CUP$GoLiteParser$parser,
    java.util.Stack            CUP$GoLiteParser$stack,
    int                        CUP$GoLiteParser$top)
    throws java.lang.Exception
    {
              return CUP$GoLiteParser$do_action_part00000000(
                               CUP$GoLiteParser$act_num,
                               CUP$GoLiteParser$parser,
                               CUP$GoLiteParser$stack,
                               CUP$GoLiteParser$top);
    }
}

}
