
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.golite.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int UMINUS = 10;
  public static final int TRUE = 5;
  public static final int INT_LITERAL = 7;
  public static final int STRING_LITERAL = 9;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int FALSE = 6;
  public static final int FLOAT_LITERAL = 8;
  public static final int error = 1;
  public static final int NOT = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "NOT",
  "TRUE",
  "FALSE",
  "INT_LITERAL",
  "FLOAT_LITERAL",
  "STRING_LITERAL",
  "UMINUS"
  };
}

